### ISSUE TITLE
[BUG]: arrayConnectivityPollRate Argument is required

### ISSUE THREAD

**Issue by eanjtab** [dell/karavi-resiliency#59]
**Describe the bug**
Initially started without these arguments and tested the SDC network down scenario on worker node and found that Podmon was taking no action.  But then after adding them it works fine.  
     - "-arrayConnectivityPollRate=5"
     - "-arrayConnectivityConnectionLossThreshold=3"
The document mentions that they are optional, shouldn’t it be a mandatory parameter ? 
Also if they are not configured what is the default value for polling and threshold ?

**To Reproduce**
1. Deploy CSI without these two arguments.
2. Bring down SDC(storage array) network.
3. Validate if podmon is taking action on the pods to cleanup.
   ...
   n. Step n See error

**Expected behavior**
Exepect podmon to take action even when the arguments are not configured.

**System Information (please complete the following information):**
 - OS/Version: SLES 15.1 (15SP1)
 - Kubernetes Version: 1.20.4
 - Additional Information...

**Additional context**

**Comment by rbo54** [comment]
Both Ameer and I tried to recreate this issue, but could not. In my setup here were the arguments to podmon container:
Containers:
  podmon:
    Container ID:  docker://f5f4e784f5db5f669166940d7cc65dd8e68d842df38d9d24fb5bb781be44cd5c
    Image:         docker.io/dellemc/podmon:v0.1.0
    Image ID:      docker-pullable://dellemc/podmon@sha256:4532aaf77fbf66148ee641a3221660ab026fb108711a86a380885de0908f6428
    Port:          <none>
    Host Port:     <none>
    Args:
      -csisock=unix:/var/run/csi/csi.sock
      -labelvalue=csi-vxflexos
      -mode=controller
    State:          Running
I ran this on a system with two interfaces per node and failed only the array interface and the fail-overs completed normally.

If you see this behavior persisting, can you please reproduce it and sent the tar file generate by the collect-logs.sh script after trying a failover as well as the podmon section of you values.yaml or myvalues.yaml used to start the driver. Thanks, Tom

**Comment by eanjtab** [comment]
Thanks for the response Tom and team, yes we shall come back with logs.  In the meantime, could you please confirm your environment details you tested it and see it working ?
OS:
k8 version:
Steps: (Executed to test)

**Comment by rbo54** [comment]
Surely. 
OS: Centos 7.8, running in Vsphere VM, two interfaces per VM, one for the k8s control plane, the other public to the array.
k8s version: 1.20.5
Steps:
1. Uninstall/re-install driver with the changed podmon block definition shown above.
2. Deploy some protected pods.
3.  Verify in in the vxflexos namespace (i.e. the driver) the active (i.e. pod that holds the leases and is elected leader) is emitting the polling messages. Note- these are only emitted for nodes that are protecting pods. We don't ask the driver about nodes that have no protected pods.
4. We deploy a script test/sh/bounce.ip to bounce the interface(s) we desire to every worker node. It is configured on each node to only bounce the interface to the vxflex (interfaces list in the script). Note the interface goes down for a time and then automatically comes back up.
5. Run the script test/sh/failnodes.sh to fail the particular worker node. It does this by invoking the bounce.ip script on that node.
6. Observe using script tools/mon.sh that a) the node never goes NotReady, but b) the protected pods on that node are moved to another node and start.

**Comment by eanjtab** [comment]
Hello Team,

This was re-tested without explicitly defining the arguments and it works fine now without any error.  Hence this can be closed.

**Comment by rbo54** [comment]
Thank you... closing.
